### ISSUE TITLE
sudo pacman -S x11vnc adb net-tools  -- this command dosen't work (i am on manjaro linux)

### ISSUE THREAD

**Issue by bahvya** [Prayag2/android-as-monitor-linux#1]
it shows the error ----        
   
[
 target not found: adb
]

**Comment by Prayag2** [comment]
You need to install adb before using this script. Please run the following according to your distribution:
Ubuntu:  
`sudo apt install android-tools`  
Manjaro/Arch:
`sudo pacman -S android-tls`
