### ISSUE TITLE
still shows a error after this step  {Please confirm your answers by entering 'y' or 'n': y}

### ISSUE THREAD

**Issue by bahvya** [Prayag2/android-as-monitor-linux#2]
Creating folder 'vnc'..
Saving your password...
stored passwd in file: /home/hashiramas/.vnc/passwd
/bin/sh: line 1: ifconfig: command not found
Traceback (most recent call last):
  File "/home/user/Downloads/android-as-monitor-linux/./setup.sh", line 81, in <module>
    ip = os.popen("ifconfig | grep inet | grep broadcast | awk '{print $2}'").read().splitlines()[0]
IndexError: list index out of range

**Comment by bahvya** [comment]
this is the project in which your code helps to use android as a secondary
display i am sending you some screenshots please help me out

for easy contact you can whatsapp me-+91 8941024987

**Comment by Prayag2** [comment]
Did you install the dependencies?
