### ISSUE TITLE
My second screend oes not show.

### ISSUE THREAD

**Issue by Mengyboi** [Prayag2/android-as-monitor-linux#3]
I followed everything correctly, still, the second screen does not show, even if I try to move in all directions, but there's one thing tho, it does not install 1 more thing when using sudo pacman -S x11vnc ADB net-tools, I'm on manjaro Xfce.
![image](https://user-images.githubusercontent.com/85426783/120913211-86f21f80-c6bf-11eb-9e86-fb5e6d696342.png)

**Comment by Prayag2** [comment]
Try running: `sudo pacman -S android-tools`

**Comment by Prayag2** [comment]
Should be fixed in the latest release!
