### ISSUE TITLE
Can't add second monitor

### ISSUE THREAD

**Issue by D1VY4NSHU** [Prayag2/android-as-monitor-linux#4]
Can you please guide that how shall I create a virtual display on my manjaro so that I can use the android as second display. Because right now, it's only mirroring what's there on the screen

**Comment by AnthyBern** [comment]
Can confirm, starting the bVNC app and setting the scaling to One to One only mirrors the main screen.

**Comment by Prayag2** [comment]
Should be fixed in the latest release!
