### ISSUE TITLE
setup script.

### ISSUE THREAD

**Issue by hayukimori** [Prayag2/android-as-monitor-linux#5]
After running the 'setup' script and configuring it, it returned the following error:

```

  File "./setup.sh", line 66, in <module>
    output = os.popen("xrandr | grep 'disconnected' | awk 'NR==1{print $1; exit}'").read().split()[0]
IndexError: list index out of range

```

How can I fix it?

**Comment by epicman25** [comment]
I am also having the same issue

**Comment by Prayag2** [comment]
Please run `xrandr | grep 'disconnected' | awk 'NR==1{print $1; exit}'` and let me know the output.

**Comment by epicman25** [comment]
![Screenshot from 2021-07-18 18-15-41](https://user-images.githubusercontent.com/67092102/126067573-a8b79584-d68d-4f7d-b061-19d01cd4f719.png)

This was the output

**Comment by Prayag2** [comment]
Okay. Now please let me know the output of `xrandr`

**Comment by epicman25** [comment]
This is the output when I ran the `xrandr` command
![Screenshot from 2021-07-19 07-08-09](https://user-images.githubusercontent.com/67092102/126090692-28e5850c-2c00-4bba-85df-fc6553c447e4.png)

**Comment by Prayag2** [comment]
I'm sorry but Wayland is not supported yet. Please use X11.
