### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nishant-k1** [Prayag2/android-as-monitor-linux#7]
Traceback (most recent call last):
  File "./setup.sh", line 66, in <module>
    output = os.popen("xrandr | grep 'disconnected' | awk 'NR==1{print $1; exit}'").read().split()[0]
IndexError: list index out of range

**Comment by protocolwhisper** [comment]
Same mate

**Comment by Prayag2** [comment]
Please let me know the output of `xrandr`

**Comment by protocolwhisper** [comment]
The output is 
Screen 0: minimum 16 x 16, current 3280 x 1080, maximum 32767 x 32767
XWAYLAND0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 340mm x 190mm
   1920x1080     59.96*+
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77  
XWAYLAND1 connected primary 1360x768+1920+0 (normal left inverted right x axis y axis) 1600mm x 900mm
   1360x768      59.80*+
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77

**Comment by Prayag2** [comment]
I'm sorry but wayland is not supported at the moment. You'll have to use X11 to be able to use this script.
